// <auto-generated />
using DotNet_grams.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNet_grams.Migrations
{
    [DbContext(typeof(PostDbContext))]
    [Migration("20190215012622_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNet_grams.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("PosterName");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "beach view",
                            PosterName = "xl",
                            URL = "https://via.placeholder.com/200?text=DotNetGram"
                        },
                        new
                        {
                            ID = 2,
                            Description = "beach view",
                            PosterName = "xxl",
                            URL = "https://via.placeholder.com/200?text=DotNetGram"
                        },
                        new
                        {
                            ID = 3,
                            Description = "cute kitty",
                            PosterName = "xxxl",
                            URL = "https://via.placeholder.com/200?text=DotNetGram"
                        },
                        new
                        {
                            ID = 4,
                            Description = "winter time",
                            PosterName = "xxxl",
                            URL = "https://via.placeholder.com/200?text=DotNetGram"
                        },
                        new
                        {
                            ID = 5,
                            Description = "happy hour",
                            PosterName = "xxxl",
                            URL = "https://via.placeholder.com/200?text=DotNetGram"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
